Repository DataDog/dd-opentracing-cpp, pull requests merged in 2018-09, with the labels that each got.

#35 Refactor for supporting external writer
  BUILD.bazel
  include/datadog/opentracing.h
  src/agent_writer.cpp
  src/agent_writer.h
  src/encoder.cpp
  src/encoder.h
  src/noopspan.h
  src/opentracing.cpp
  src/opentracing_agent.cpp
  src/opentracing_external.cpp
  src/propagation.cpp
  src/span.cpp
  src/span.h
  src/span_buffer.h
  src/tracer.cpp
  src/tracer.h
  src/tracer_factory.cpp
  src/transport.h
  src/writer.cpp
  src/writer.h
  test/CMakeLists.txt
  test/agent_writer_test.cpp
  test/opentracing_test.cpp
  test/tracer_factory_test.cpp
Labels: enhancement

#44 Allow choosing which source dependencies are built
  .circleci/config.yml
  README.md
  examples/nginx-tracing/Dockerfile
  scripts/install_dependencies.sh
Labels: dev/tooling, enhancement

#45 Ensure RNG seeded at fork
  src/tracer.cpp
Labels: bug

#46 Be more careful with URL id-stripping
  src/span.cpp
  test/span_test.cpp
Labels: bug

#49 Priority Sampling
  CMakeLists.txt
  include/datadog/opentracing.h
  src/agent_writer.cpp
  src/agent_writer.h
  src/encoder.cpp
  src/encoder.h
  src/noopspan.cpp
  src/noopspan.h
  src/opentracing_agent.cpp
  src/opentracing_external.cpp
  src/propagation.cpp
  src/propagation.h
  src/sample.cpp
  src/sample.h
  src/span.cpp
  src/span.h
  src/span_buffer.cpp
  src/span_buffer.h
  src/tracer.cpp
  src/tracer.h
  src/tracer_factory.cpp
  src/transport.cpp
  src/transport.h
  src/version_check.cpp
  src/writer.cpp
  src/writer.h
  test/agent_writer_test.cpp
  test/integration/nginx/expected.json
  test/integration/nginx/nginx.conf
  test/integration/nginx/nginx_integration_test.sh
  test/mocks.h
  test/propagation_test.cpp
  test/sample_test.cpp
  test/span_buffer_test.cpp
  test/span_test.cpp
  test/tracer_factory_test.cpp
  test/tracer_test.cpp
Labels: enhancement

#48 Adds language version number and better checking for library version number
  src/encoder.cpp
  src/version_number.h.in
  test/agent_writer_test.cpp
Labels: dev/tooling

#53 Upgrade to OpenTracing 1.5.0
  .circleci/config.yml
  .gitignore
  CMakeLists.txt
  scripts/install_dependencies.sh
  src/dynamic_load.cpp
  src/version_check.cpp
  src/version_check.h
  test/CMakeLists.txt
  test/integration/nginx/Dockerfile
  test/version_check_test.cpp
Labels: core, dev/tooling, enhancement

#55 Fix support for multiple artifacts
  scripts/release.sh
Labels: bug, dev/tooling
